// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHh5MOgqvm_fbY__4o6dC107SPJQAmf0',
    appId: '1:1013792169057:web:e3bc2df90605502a41de20',
    messagingSenderId: '1013792169057',
    projectId: 'simple-money-tra',
    authDomain: 'simple-money-tra.firebaseapp.com',
    storageBucket: 'simple-money-tra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCJ9vlEKdxjZJuNxOU-sTBXaiNJ2qvbw',
    appId: '1:1013792169057:android:5e583e44bd6c9d5541de20',
    messagingSenderId: '1013792169057',
    projectId: 'simple-money-tra',
    storageBucket: 'simple-money-tra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCeJmLg9NVR6UKe0ECRGhx1Gc5fsO-Fbs',
    appId: '1:1013792169057:ios:bb3f6eda4eeb9a0041de20',
    messagingSenderId: '1013792169057',
    projectId: 'simple-money-tra',
    storageBucket: 'simple-money-tra.appspot.com',
    iosClientId: '1013792169057-b85cgjif01me80spn0v63aebrd0hkhqa.apps.googleusercontent.com',
    iosBundleId: 'com.kimapp.simpleMoneyTracker',
  );
}
